### PR TITLE
Add Ramps 1.4 Board Support

### PR DESCRIPTION
**Pull request by docwelch**
Changes based on @jekhor’s work
Uses D8 as the spindle pin

### CODE REVIEW

**Comment by chamnit** [comment]
@docwelch : Looks pretty good. I may have some time tonight to finally dig into this and do some testing. If not, I'll get it done this weekend. Thanks again.

**Comment by mliles95** [comment]
@chamnit : Hi and thank you for all of your hard work with this. I'm just starting to set up a CNC unit with the mega/ramps1.4 combo. Do I understand this correctly that you were able to add support for ramps 1.4?

**Comment by chamnit** [comment]
@mliles95 : Sorry this fell off my radar. I have a big presentation coming up tomorrow at my day job and its been weighing heavily on my mind. Once it's over, I'll be able to get back to integrating RAMPs support officially into this branch. Right now, it's only a pull request. You can use @docwelch version until then,

**Comment by mliles95** [comment]
I'm so new at this that I don't even know what a pull request even is. But I'll do my best to try and figure this out. Focus on your Job and if you find some time for me please do but don't worry about it. I hope things at work become less taxing for you soon . Don't stress yourself out. I will see if I can find the other version you suggested for me . Thank you for getting back to me so quickly too.

**Comment by docwelch** [comment]
@mliles95: you can go to my Github site where I have created the version of GRBL that works with a Ramps 1.4 board. You will download that version and use the usual directions to create a library to use with your Arduino Mega/Ramps 1.4 setup. See: [docwelch Ramps 1.4 Github](https://github.com/docwelch/grbl-Mega/tree/Ramps-1.4). I have been using it on my small 3.5 W laser engraver and it seems to work well.

**Comment by mliles95** [comment]
Thank you very much Steven. I appreciate you for that.

**Comment by mliles95** [comment]
I'm going to 1.download the .hex file from your repo 2.flash my Arduino Mega with the .hex file. 3.I assume that I will need to change things in the code like e steps, printer parameters and so fourth? If so how? Is there a configuration file that I can edit in Notepad++? 4. Then control the unit with a program like Universal g-code sender?

**Comment by chamnit** [comment]
@docwelch : I finally got some time to sit down and look over this. So, in short, I'll merge it shortly, but I will be noting it as a temporary solution. To do this right, I need to upgrade the Grbl codebase and comm protocol to account for things like how to report max/min limit pins and how to tell GUIs that there are extra axes in this particular build. These things have been planned already, but this is a good reason to start working on this.

**Comment by mliles95** [comment]
That would be great wonderful a great big help for people like myself. If you think that it can be done

**Comment by docwelch** [comment]
@chamnit: Sounds good.

**Comment by mliles95** [comment]
I downloaded it . The only file I could find that I could open in the arduino ide was under examples. When I open it there's only an instruction to include another file. I'm so lost could you instruct me on how to set it up before flashing the arduino please? Thank you

**Comment by grexa178** [comment]
Hi, I have same problem as mliles95. I think it includes files containing code and writing it to arduino. I was also trying to flash .hex file. Flashed successfully but no response from arduino when testing with universal g code sender. I plan to use my arduino with ramps shield as motor driver for OppenPNP.

**Comment by swarfer** [comment]
1 - make sure to remove any and all other grbl libraries from the arduino libraries folder
2 - follow the instructions at https://github.com/gnea/grbl/wiki/Compiling-Grbl for the install

**Comment by mliles95** [comment]
David, ok I'll try the link you included and see if I can install it. Thank you for all your help and also thanks to everyone here helping us

**Comment by chamnit** [comment]
I haven't yet tested how the RAMPS pull request works, if it does, but there isn't any reason why it shouldn't. The .hex file in the release page is for the standard build, not RAMPS. To enable RAMP support, you'll need to edit the config.h file and uncomment a couple of lines at the top of the file.

**Comment by mliles95** [comment]
Sonny, I have no idea how any of it works lol

**Comment by mliles95** [comment]
Ok I have compiled but before I flash it I want to make sure it's the correct version GRBL_VERSION "1.1e" BUILD "20170114" Is this correct?

**Comment by electrokean** [comment]
@mliles95 The latest version here has the following in grbl.h
#define GRBL_VERSION "1.1f"
#define GRBL_VERSION_BUILD "20170717"

**Pull request merged**
